### ISSUE TITLE
Authentication module

### ISSUE THREAD

**Issue by Air-Git** [microsoftgraph/powershell-intune-samples#114]
It would be great if there were a PSGallery authentication module for the Graph API. Many of the sample scripts have the same or similar authentication functions. If there were a module we could authenticate in scripts similar to "connect-AzureAD".

**Comment by tabs-not-spaces** [comment]
you can actually use any authentication modules that are currently available - all that is required is the ability to define the application id so that you can point it to either the generic intune application id, or your own created application.

I'd suggest as the code contained in this repository is just "sample code" it is meant to show the possibilities of interacting with intune programmatically.
