### ISSUE TITLE
How do I force a logout / force the user token to expire

### ISSUE THREAD

**Issue by abulgatz** [microsoftgraph/powershell-intune-samples#153]
I am exporting from one tenant and importing into another.

How do I kill the global authtoken or force the user token for the current login to expire, so that I can login to a different tenant?

**Comment by SGeeves** [comment]
If you add in the 2 at the end of the script;
Clear-Variable -Name user
Clear-Variable -Name authToken

The above worked for me as I need to run this for 5 clients at the same time. Works with no issues for me.

**Comment by davefalkus** [comment]
As per @SGeeves you can clear the variables using Clear-variable.

The sample scripts make the authToken global so available throughout the powershell session. 

$global:authToken = Get-AuthToken -User $User

You could remove the global so that it only exists in the session, but that would mean you need to re-authenticate every time a script is ran

$authToken = Get-AuthToken -User $User
