### ISSUE TITLE
Automate the sign in

### ISSUE THREAD

**Issue by TheMaster870** [microsoftgraph/powershell-intune-samples#172]
Is there any way to automate the access token sign in box?
Backstory:
I have modified the ManagedDevices_Get.ps1 to save details about devices into a CSV which then gets sent and imported into our asset manager.
At the moment I haft to run it manually as it asks for my password to authorise the Intune access.
I am looking for a way to have it run automatically on a server every night or so.
Thanks for any help

**Comment by taspanja** [comment]
Hi Drew,

You can use the powershell snippet to encrypt the password as a securestring outputting it to a safe location on the machine

`Read-Host -AsSecureString | ConvertFrom-SecureString | Out-File C:\FilePath\pass.txt`

Then within your script you can call the credential module as per below snippet

` $Pass = Get-Content 'C:\FilePath\pass.txt' | ConvertTo-SecureString`
`$Credential = New-Object System.Management.Automation.PSCredential ("username@domain.com", $Pass)`

After that you can practically provide that credential to the system instead of inputting it manually. If the script works then you can put it on a scheduled task to repeat however many times you need it per day. Make sure to exclude the service account that you will use on the script from any MFA configurations/requirements you might have in place.

**Comment by TheMaster870** [comment]
Hi, Thanks for your help.

I've tried using this [article](https://blog.tyang.org/2017/06/12/powershell-function-to-get-azure-ad-token/) to get a token but get the error:
`Cannot find an overload for "AcquireTokenAsync" and the argument count: "3"`

I can see there is no overload for [AcquireTokenAsync](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.clients.activedirectory.authenticationcontext.acquiretokenasync?view=azure-dotnet) with these 3 parameters but am struggling to find another way to implement it.

This is what I've got so far:
```
$clientId = 'ClientID'
$ADAuthorityURL = "https://login.microsoftonline.com/$Tenant"
$redirectUri = "urn:ietf:wg:oauth:2.0:oob"
$resourceURL = "https://graph.microsoft.com"

$AADuserName = "EmailAddress"
$Pass = Get-Content 'C:\Upload\pass.txt' | ConvertTo-SecureString
$Credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $AADuserName, $Pass
$Username = $Credential.Username
$Password = $Credential.Password

$AADcredential = [Microsoft.IdentityModel.Clients.ActiveDirectory.ClientCredential]::new($UserName, $Password)
$authContext = [Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext]::new($ADAuthorityURL)
$authResult = $authContext.AcquireTokenAsync($resourceURL,$clientId,$AADcredential)```

**Comment by TheMaster870** [comment]
Only asks for password once in a PS session.
So made PS script that runs once, put in password, runs script, waits 1 hour then repeats and doesn't ask for password.
