### ISSUE TITLE
Refresh the access token

### ISSUE THREAD

**Issue by noblevarghese** [microsoftgraph/powershell-intune-samples#92]
Hi,

How can I refresh the access token, if it is about to expire. In our case, we have more than 1.8Lakh users. So if the script runs for more than an hour, it breaks. I would like to know how to renew the token with MFA is enabled for the user.

Thanks!

**Comment by tabs-not-spaces** [comment]
The response object you get back from the oauth2.0 request sends you back not only the required authentication token, but details on when the token will expire and a refresh token. you need to write your own logic to check the expiry time against the current time and using the refresh token, request an update. If you would like, I can link you to sample code that shows this in practice.

**Comment by Air-Git** [comment]
Yes please! All the sample code has the same functions for getting an auth token. But, when the token has expired, they don't get a fresh token. They just tell you it has expired!

**Comment by tabs-not-spaces** [comment]
easy - leave it with me.

**Comment by davefalkus** [comment]
Hi all,

There is sample code in the following script that uses a function Test-AuthToken which will do the auto refresh.

https://github.com/microsoftgraph/powershell-intune-samples/blob/master/AppProtectionPolicy/ManagedAppPolicy_AppRegistrationSummary.ps1

Would that work for you?

Thanks
Dave

**Comment by Air-Git** [comment]
Ah, I see what has happened. The Get-AuthToken is generic, but different sample scripts have implemented the check in different ways. In some scripts it is in the body of the code so, if it has expired, it is not refreshed. Whereas if we have the "Connect" in a separate function then we can call it before making the request.
Thanks for point it out.

**Comment by tabs-not-spaces** [comment]
I'll try and find some time to standardize the authentication for all sample code in the repo so it uses the test-authtoken function.

**Comment by davefalkus** [comment]
We are looking at adding sample scripts that use the Intune PowerShell module:
https://www.powershellgallery.com/packages/Microsoft.Graph.Intune/6.1907.1.0

The module supports the auto-refresh of the token out of the box without additional code.

Would this help rather than updating all sample code with the test-authtoken function? 

Dave

**Comment by Air-Git** [comment]
This is terrific. I didn't know it existed. It makes most sense for sample scripts to use this module instead of repeating the authentication.
The "sample scripts" confused me for a long time. For example, if I use "Get-AzureADDevice" then I might need a sample script to show me how to work with the output. But these "sample scripts" are actually writing functions like "Get-IntuneDevice" (with the Graph API), and then working with the output.
You could have an extensible series of modules for different GET and POST commands, followed by sample scripts showing how to use them.

**Comment by davefalkus** [comment]
Thanks for the feedback. The sample script in this repository were created with the same authentication function for every script to show how you can use Graph with PowerShell, We heard the feedback early about a PowerShell module so we created it in February this year.

We will most likely keep the sample code as is, but then add sample code that use the module instead. We've just done our July release which added support for Azure Automation.

Please close the issue if this addresses your issue.

Thanks
Dave
